export const DOOR_CONSTANTS = {
  INITIAL_WIDTH: 2,
  INITIAL_HEIGHT: 3,
  DOOR_DEPTH: 0.1,
  DOOR_GAP: 0.02,
  MAX_OPEN_ANGLE: Math.PI * 0.8,
  HANDLE_RADIUS: 0.1,
  HANDLE_HEIGHT: 0.3,
  HANDLE_SEGMENTS: 32,
  HANDLE_POSITION_RATIO: 0.9,
  HANDLE_Z_OFFSET: 0.1,
  DOOR_COLOR: 0x8b4513,
  MIN_SIZE: 0.5,
  MAX_DOOR_HEIGHT: 5.6,
  MAX_DOOR_WIDTH: 3.6,
  ROTATION_THRESHOLD: 0.001,
  ROTATION_SENSITIVITY: 1.5,
} as const;

export const HOUSE_CONSTANTS = {
  DEFAULT_WIDTH: 8,
  DEFAULT_HEIGHT: 6,
  DEFAULT_DEPTH: 0.1,
  WALL_COLORS: {
    FRONT: 0xffffff,
    BACK: 0x8b7355,
    ROOF: 0x8b7355,
    ROOF_BACK: 0x8b4513,
  },
} as const;

export const UI_CONSTANTS = {
  BASE_COLOR: 0x8b4513,
  HIGHLIGHT_COLOR: 0xffd700,
  PULSE_SPEED: 2,
  PULSE_MIN: 0.3,
  PULSE_MAX: 1.0,
} as const;
